### ISSUE TITLE
admin login issue

### ISSUE THREAD

**Issue by hamsaaaa897** [mohangowdatdev/online-voting-system-DBMS-Project#1]
hi brother when i am trying to login into admin acc it is saying they is no acc with username . what is the solution please

**Comment by mohangowdatdev** [comment]
did you try using 

username:  mohan
password:  mohan.sjbit

if yes and its still not working post a picture while recommenting

**Comment by hamsaaaa897** [comment]
> did you try using
> 
> username: mohan password: mohan.sjbit
> 
> if yes and its still not working post a picture while recommenting

bro worked thanks i can use this for my project right

**Comment by hamsaaaa897** [comment]
> did you try using
> 
> username: mohan password: mohan.sjbit
> 
> if yes and its still not working post a picture while recommenting

**Comment by hamsaaaa897** [comment]
> > did you try using
> > username: mohan password: mohan.sjbit
> > if yes and its still not working post a picture while recommenting

and can i edit the voters and candidates name if possbile
